35-logging :: Added Logging functionality to project
galaxybomb23/ECE461-Software-Engineering pull request #42
Opened 2024-09-13 04:41 UTC by RushilShaw

Added all the specifications in the "Added Logging Issue"

2024-09-15 17:28 UTC, Coop8 reviewed
Looks good, good work

2024-09-15 17:28 UTC, Coop8 commented on src/Metrics.ts
> +            logger.error(`${url} is an valid Github URL`);
Shouldn't this be invalid?

2024-09-15 18:11 UTC, RushilShaw commented on src/Metrics.ts
> +            logger.error(`${url} is an valid Github URL`);
Yup! I will fix push a fix for this.

2024-09-15 18:16 UTC, galaxybomb23 requested changes
Lotta things here. Mainly pull from #21 since there was a lot of ouput updates there in order to meet the checker standards

2024-09-15 18:16 UTC, galaxybomb23 commented on .github/workflows/ci.yaml
Changes here will immediately be overwritten by #39 / #21. this file should not be changed. It doesn't involve "logging"

2024-09-15 18:16 UTC, galaxybomb23 commented on src/busFactor.ts
> -        // print total number of commits 📝
the 📝 means this should be a debug level logging. NOT DELETED

2024-09-15 18:16 UTC, galaxybomb23 commented on src/cli.ts
> +    logger.info(`Tests Passed: ${passedTests}`);
i think this needs to be process.std.write()
check #39

2024-09-15 18:16 UTC, galaxybomb23 commented on src/cli.ts
> +    if (failedTests / (passedTests + failedTests) > 0.05) {      //if more than 5% of the tests fail, exit with error
Remove this, Checker in #39 does this now

2024-09-15 18:16 UTC, galaxybomb23 commented on src/cli.ts
> +    await sleep(1000);
slowing down the code? no?

2024-09-15 18:16 UTC, galaxybomb23 commented on src/netScore.ts
> -            console.log(`BusFactor: ${this.busFactor.busFactor}`);
why are we deleting this? This should be Debug? There was significant issues in calculating NetScore, so knowing what its working with (the metrics) is important for debug.

2024-09-15 20:34 UTC, galaxybomb23 commented
fixed merge conflicts

2024-09-15 23:31 UTC, Coop8 approved these changes
Does not look good to me

2024-09-15 23:38 UTC, galaxybomb23 requested changes
There seems to be an issue where the main you pulled from was pre #39  and thus you've overwritten some of the work done in #21. not sure how This will play out

2024-09-15 23:38 UTC, galaxybomb23 commented on src/cli.ts
> +    logger.info(`Coverage: ${coverage}%`);
why is this in info?? This is needed by the Checker... as seen in 

commit 611f8ccd2665ae08213f95a22b652fc8948a2914

2024-09-15 23:38 UTC, galaxybomb23 commented on src/Metrics.ts
>      throw new Error('API_TOKEN is not defined in the .env file');
GITHUB_TOKEN not API

2024-09-15 23:38 UTC, galaxybomb23 commented on src/cli.ts
> +    process.stdout.write(`Tests Failed: ${failedTests}\n`);
this was removed/updated in #21 ... how is this still here?

2024-09-16 01:46 UTC, galaxybomb23 approved these changes

2024-09-16 01:49 UTC, Coop8 approved these changes
Now we are talking 😎

2024-09-16 01:54 UTC, merged

2024-09-16 01:56 UTC, galaxybomb23 commented
finally, 
![image](https://github.com/user-attachments/assets/ce845993-512a-4162-91ac-ff09191584f1)